package commInfra;

public enum MessageType {
    CLOSE_PS,
    PS_IS_OPEN,
    CONDUCTSURVEY,
    PUBLISHRESULTS,
    VOTER_CHOOSEN,
    CALLFORSURVEY,
    EP_ISOPEN,
    CHECK_ID,
    GATHERING_VOTES,
    PUBLISH_ELECTION_RESULTS,
    GET_VOTES_COUNT,
    VOTE,
    GET_VOTE,
    OPEN_PS,
    CALL_NEXT_VOTER,
    PS_IS_EMPTY,
    MAX_VOTES,
    PS_IS_CLOSED_AFTER,
    CAN_ENTER_PS,
    EXITING_PS,
}
